name: recap
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - numpy
  - pandas
  - matplotlib
  - pytorch
  - torchvision 
  - torchmetrics
  - tqdm
  - pyyaml
  - ignite 
  - pip:
    - stability-sdk